@startuml


:Agente: -right-> (Enviar Solicitud de Credito)
(Enviar Solicitud de Credito) <|-- (Enviar\n solicitud de credito personal)
(Enviar Solicitud de Credito) <|-- (Enviar\n solicitud de credito empresarial)



@enduml