@startuml

left to right direction

:Socio: as s
:Biblioteca: as b

rectangle Biblioteca{
s -- (Reservar Libro)
s -- (Prestar Libro)
s -- (Devolver Libro)
b -- (Prestar Libro)
b -- (Actualizar Catalogo)
}


@enduml