@startuml

left to right direction

:Actor: as a
:Actor1: as a1

rectangle sistema{
usecase "(Caso de uso)"
usecase "(Caso de uso1)"
usecase "(Caso de uso2)"
}

a -- (Caso de uso)
a -left- (Caso de uso1)
:Actor: -left- (Caso de uso2)
:Actor1: -right- (Caso de uso2)
:Actor1: -right- (Caso de uso1)

@enduml